const demo=[
{brand:'Toshiba',model:'GR-RS910WI-PMTH(06)',image:'',type:'SBS',channel:'Power Buy',grossL:711,netL:711,door:'玻璃',iceMaker:'No',officialPrice:35990,promoPrice:28990,monthlySales:'',sellingPoints:'711L / Origin Inverter / Pure Air Turbo / TSmartLife',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/TOSHIBA-Side-by-Side-Refrigerator-25-1-Cubic-Inverter-Grey-GR-RS910WI-PMTH06-306586'},
{brand:'Toshiba',model:'GR-RS905WIA-PGTH(22)',image:'',type:'SBS',channel:'Power Buy',grossL:711,netL:711,door:'黑色玻璃',iceMaker:'Yes',officialPrice:42990,promoPrice:29990,monthlySales:'',sellingPoints:'711L / Pure Air Turbo / 自动制冰 / Pure Ice / TSmartLife',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/TOSHIBA-Side-by-Side-Refrigerator-25-1-Cubic-Inverter-Black-GR-RS905WIA-PGTH22-306583'},
{brand:'Samsung',model:'RS62R5001B4/ST',image:'',type:'SBS',channel:'Power Buy',grossL:655,netL:655,door:'Inox Gray',iceMaker:'待核实',officialPrice:36990,promoPrice:31444,monthlySales:'',sellingPoints:'655L / SpaceMax / All-around Cooling / Digital Inverter',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/samsung-os-%E0%B8%95%E0%B8%B9%E0%B9%89%E0%B9%80%E0%B8%A2%E0%B9%87%E0%B8%99-sbs-23-1-%E0%B8%84%E0%B8%B4%E0%B8%A7-samsung-rs62r5001b4st-263270'},
{brand:'Samsung',model:'RS70F65Q2FST',image:'',type:'SBS',channel:'Power Buy',grossL:655,netL:655,door:'Black Doi',iceMaker:'Yes',officialPrice:30990,promoPrice:24990,monthlySales:'',sellingPoints:'655L / SpaceMax / AI Inverter / Wi-Fi / SmartThings',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-SpaceMax-Technology-Side-by-Side-Refrigerator-23-1-Cubic-Inverter-Black-Doi-RS70F65Q2FST-304751'},
{brand:'Samsung',model:'RS70F65K1BST',image:'',type:'SBS',channel:'Power Buy',grossL:635,netL:635,door:'Clean Black',iceMaker:'Yes',officialPrice:48990,promoPrice:29990,monthlySales:'',sellingPoints:'635L / SpaceMax / AI Inverter / Wi-Fi / 冰水一体',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-SpaceMax-Technology-Side-by-Side-Refrigerator-22-4-Cubic-Inverter-Clean-Black-RS70F65K1BST-304745'},
{brand:'Samsung',model:'RS80F65G1FST',image:'',type:'SBS',channel:'Power Buy',grossL:627,netL:627,door:'Black Doi',iceMaker:'Yes',officialPrice:54990,promoPrice:45990,monthlySales:'',sellingPoints:'627L / Food Beverage Showcase / Auto Open Door / AI Inverter',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-Food-Beverage-Showcase-Side-by-Side-Refrigerator-22-1-Cubic-Inverter-Black-Doi-RS80F65G1FST-304754'},
{brand:'Samsung',model:'RS90F65A2FST',image:'',type:'SBS',channel:'Power Buy',grossL:615,netL:615,door:'Black Doi',iceMaker:'Yes',officialPrice:80990,promoPrice:72990,monthlySales:'',sellingPoints:'615L / Family Hub / AI Inverter / Wi-Fi / 冰水一体',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-Family-Hub-Side-by-Side-Refrigerator-21-7-Cubic-Inverter-Black-Doi-RS90F65A2FST-304757'},
{brand:'Samsung',model:'RS90F65D2FST',image:'',type:'SBS',channel:'Power Buy',grossL:615,netL:615,door:'Black Doi',iceMaker:'Yes',officialPrice:64990,promoPrice:56990,monthlySales:'',sellingPoints:'615L / 9-inch LCD AI Home / Bixby / SmartThings',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-LCD-AI-Home-Side-by-Side-Refrigerator-21-7-Cubic-Inverter-Black-Doi-RS90F65D2FST-304760'},
{brand:'LG',model:'GC-B257KGHW.ABMPLMT',image:'',type:'SBS',channel:'Power Buy',grossL:664,netL:664,door:'黑色玻璃',iceMaker:'No',officialPrice:32990,promoPrice:28590,monthlySales:'',sellingPoints:'664L / Smart Inverter / LinearCooling / Multi Air Flow',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/LG-Side-by-Side-Refrigerator-23-4-Cubic-Inverter-Black-Glass-GC-B257KGHW-ABMPLMT-306752'},
{brand:'LG',model:'GC-B257KLJW.APYPLMT',image:'',type:'SBS',channel:'Power Buy',grossL:664,netL:664,door:'银色',iceMaker:'待核实',officialPrice:28900,promoPrice:24890,monthlySales:'',sellingPoints:'664L / Smart Inverter / Multi Air Flow / 节能',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/LG-Side-by-Side-Refrigerator-23-4-Cubic-Inverter-Silver-GC-B257KLJW-APYPLMT-303177'},
{brand:'LG',model:'GC-X257ELEP.APYPLMT',image:'',type:'SBS',channel:'Power Buy',grossL:'',netL:'待核实',door:'银色',iceMaker:'待核实',officialPrice:52990,promoPrice:41900,monthlySales:'',sellingPoints:'22.2 cu.ft / Inverter / 高端系列',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/category/home-appliance/refrigerators/side-by-side-refrigerators'},
{brand:'Haier',model:'HRF-SBS636MS',image:'',type:'SBS',channel:'Power Buy',grossL:616,netL:616,door:'黑色',iceMaker:'待核实',officialPrice:25990,promoPrice:19490,monthlySales:'',sellingPoints:'616L / Twin Inverter / H-Deo Fresh / HCS Plus / Multi Airflow',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/HAIER-Side-by-Side-Refrigerator-21-7-Cubic-Inverter-Black-HRF-SBS636MS-296070'},
{brand:'Haier',model:'HRF-SBS636IW',image:'',type:'SBS',channel:'Power Buy',grossL:616,netL:616,door:'黑色',iceMaker:'Yes',officialPrice:37990,promoPrice:32841,monthlySales:'',sellingPoints:'616L / Auto Ice / H-Deo Fresh / Haismart',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/HAIER-Side-by-Side-Refrigerator-21-8-Cubic-Black-HRF-SBS636IW-302737'},
{brand:'Hitachi',model:'HRSN9713ESUTH',image:'',type:'SBS',channel:'Power Buy',grossL:656,netL:656,door:'黑色',iceMaker:'Twist Ice Maker',officialPrice:27990,promoPrice:23999,monthlySales:'',sellingPoints:'656L / Dual Surround Cooling / Triple Power Filter / Selectable Zone',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/HITACHI-Side-by-Side-Refrigerator-23-2-Cubic-Inverter-Black-HRSN9713ESUTH-307251'},
{brand:'Hitachi',model:'HRSN9698ESICMGWTH',image:'',type:'SBS',channel:'Power Buy',grossL:637,netL:637,door:'哑光玻璃白',iceMaker:'Yes',officialPrice:44990,promoPrice:41990,monthlySales:'',sellingPoints:'637L / 自动制冰与出水 / Dual Sensor / HOMEWHIZ',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/HITACHI-Skyline-Luxury-Side-by-Side-Refrigerator-22-5-Cubic-Inverter-Matte-Glass-White-HRSN9698ESICMGWTH-313903'},
{brand:'Electrolux',model:'ESE6205B-B',image:'',type:'SBS',channel:'Power Buy',grossL:624,netL:624,door:'黑色玻璃',iceMaker:'待核实',officialPrice:38990,promoPrice:28990,monthlySales:'',sellingPoints:'624L / GreenZone / DynamicAir / Inverter / QuickFreeze',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/ELECTROLUX-Side-by-Side-Refrigerator-22-Cubic-Inverter-Black-Glass-ESE6205B-B-306352'},
{brand:'Electrolux',model:'ESE6200B-B',image:'',type:'SBS',channel:'Power Buy',grossL:624,netL:624,door:'哑光黑',iceMaker:'待核实',officialPrice:35990,promoPrice:26990,monthlySales:'',sellingPoints:'624L / GreenZone / DynamicAir / Inverter / QuickChill',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/ELECTROLUX-Side-by-Side-Refrigerator-22-Cubic-Inverter-Matte-Black-ESE6200B-B-306355'},
{brand:'TCL',model:'RT62MPSBG',image:'',type:'SBS',channel:'Power Buy',grossL:631,netL:631,door:'不锈钢',iceMaker:'Twist Ice Maker',officialPrice:18490,promoPrice:15490,monthlySales:'',sellingPoints:'631L / Twin Eco Inverter / Power Cool & Freeze / AAT',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/TCL-P650-Series-Side-by-Side-Refrigerator-22-3-Cubic-Inverter-Stainless-RT62MPSBG-304128'},
{brand:'Sharp',model:'SJ-SBS600P-DK',image:'',type:'SBS',channel:'HomePro',grossL:599.6,netL:599.6,door:'钢板',iceMaker:'待核实',officialPrice:'',promoPrice:'',monthlySales:'',sellingPoints:'约600L / J-Tech Inverter / Ag+Cu Nano Deodorizer',updated:'2026-09-15',link:'https://www.homepro.co.th/p/1254182'},
{brand:'Hisense',model:'RS808N4TBMU',image:'',type:'SBS',channel:'Central',grossL:612.7,netL:612.7,door:'Mirror Glass',iceMaker:'待核实',officialPrice:31990,promoPrice:25191,monthlySales:'',sellingPoints:'612.7L / All Zone Active Hygiene+ / Inverter Pro Super Freeze / Multi Air Flow / Digital Touch',updated:'2026-09-15',link:'https://hisense.co.th/product/rs808n4tbmu/'}
];

let products=[...demo];
const $=id=>document.getElementById(id);
const money=n=>n!==''&&n!=null&&!isNaN(Number(n))?'฿'+Number(n).toLocaleString('en-US'):'—';
const brandColors={LG:'#c51d48',Haier:'#0874c9',Toshiba:'#e01c73',Hisense:'#078f91',Samsung:'#2372c7',Hitachi:'#ec6a2c',Sharp:'#7c55c8',TCL:'#ef7b25',Electrolux:'#2f8c69'};

function fillFilters(){
  const fill=(id,key,label)=>{const vals=[...new Set(products.map(x=>x[key]).filter(Boolean))].sort();$(id).innerHTML='<option value="">All / 全部'+(label?' '+label:'')+'</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')};
  fill('brand','brand');fill('type','type');fill('channel','channel');
}
function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[m]));}
function inCap(x,v){if(!v)return true;const n=Number(x.netL);if(!Number.isFinite(n))return false;if(v==='600+')return n>=600;if(v==='500-599')return n>=500&&n<600;if(v==='400-499')return n>=400&&n<500;return n>=300&&n<400}
function inPrice(x,v){if(!v)return true;const n=Number(x.promoPrice);if(!Number.isFinite(n))return false;const [a,b]=v.split('-').map(Number);return n>=a&&n<=b}
function filtered(){const b=$('brand').value,t=$('type').value,c=$('capacity').value,p=$('price').value,ch=$('channel').value,s=$('search').value.trim().toLowerCase();return products.filter(x=>(!b||x.brand===b)&&(!t||x.type===t)&&(!ch||x.channel===ch)&&inCap(x,c)&&inPrice(x,p)&&(!s||JSON.stringify(x).toLowerCase().includes(s)))}
function avg(arr){const p=arr.map(x=>Number(x.promoPrice)).filter(Number.isFinite);return p.length?Math.round(p.reduce((a,b)=>a+b,0)/p.length):null}
function renderStats(list){
  const names=['LG','Haier','Toshiba','Hisense'];
  const cards=[`<div class="stat" style="--accent:#07878a"><small>RESULTS / 当前结果</small><b>${list.length}</b><em>SKU</em></div>`];
  names.forEach(n=>{const rows=list.filter(x=>x.brand===n),a=avg(rows);cards.push(`<div class="stat" style="--accent:${brandColors[n]}"><small>${n.toUpperCase()} AVG / 均价</small><b>${a?money(a):'—'}</b><em>${rows.length} SKU</em></div>`)});
  const ta=avg(list.filter(x=>x.brand==='Toshiba')),ha=avg(list.filter(x=>x.brand==='Hisense'));const gap=ta&&ha?ta-ha:null;
  cards.push(`<div class="stat ${gap>0?'negative':''}" style="--accent:#07878a"><small>TOSHIBA - HISENSE</small><b>${gap==null?'—':(gap>=0?'+':'')+money(gap)}</b><em>Average price gap / 均价差</em></div>`);
  $('stats').innerHTML=cards.join('');
}
function productCard(x){const disc=Number(x.officialPrice)&&Number(x.promoPrice)?Math.round((1-Number(x.promoPrice)/Number(x.officialPrice))*100):0;return `<a class="productCard" style="--brand:${brandColors[x.brand]||'#07878a'}" href="${esc(x.link||'#')}" target="_blank" rel="noopener"><div class="productImg">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.model)}">`:'产品图'}</div><div><div class="pcTop"><span class="pcType">${esc(x.channel||x.type||'')}</span>${disc?`<span class="discount">-${disc}%</span>`:''}</div><div class="pcModel">${esc(x.model)}</div><div class="pcMeta">${esc(x.netL||x.grossL||'—')}L · ${esc(x.door||'')}</div><div class="pcPoint">${esc(x.sellingPoints||'')}</div><div class="pcPrice"><b>${money(x.promoPrice)}</b>${x.officialPrice?`<s>${money(x.officialPrice)}</s>`:''}</div></div></a>`}
function renderMap(list){
  const brands=[...new Set(list.map(x=>x.brand).filter(Boolean))];
  const rows=[...new Set(list.map(x=>Number(x.promoPrice)).filter(Number.isFinite))].sort((a,b)=>b-a);
  const cols=brands.length||1;let html=`<div class="map" style="--cols:${cols}"><div class="mapHeader"><div class="priceHead">Online price /<br>网上价格</div>${brands.map(b=>`<div class="brandHead" style="color:${brandColors[b]||'#07878a'}">${esc(b)}</div>`).join('')}</div>`;
  rows.forEach(price=>{html+=`<div class="mapRow"><div class="priceCell">${money(price)}</div>${brands.map(b=>{const x=list.find(y=>y.brand===b&&Number(y.promoPrice)===price);return `<div class="productCell">${x?productCard(x):''}</div>`}).join('')}</div>`});
  html+=`</div>`;if(!rows.length)html='<div style="padding:40px;text-align:center;color:#718087">没有符合条件的有价格型号。</div>';$('mapWrap').innerHTML=html;$('mapTitle').textContent=`${$('channel').value||'All / 全部'} · ${$('brand').value||'All / 全部'}`;
}
function render(){const list=filtered();renderStats(list);renderMap(list);$('topUpdated').textContent=list.map(x=>x.updated).filter(Boolean).sort().pop()||'—'}
['brand','type','channel','capacity','price','search'].forEach(id=>$(id).addEventListener('input',render));
$('reset').onclick=()=>{['brand','type','channel','capacity','price','search'].forEach(id=>$(id).value='');render()};
$('refreshBtn').onclick=()=>location.reload();
$('saveUrl').onclick=()=>{localStorage.sheetUrl=$('sheetUrl').value.trim();$('sourceMsg').textContent='数据源地址已保存'};
$('loadSheet').onclick=async()=>{const u=$('sheetUrl').value.trim()||localStorage.sheetUrl;if(!u)return $('sourceMsg').textContent='请先填写 Google Sheets CSV 地址';try{const txt=await fetch(u).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.text()});products=parseCSV(txt);if(!products.length)throw Error('empty');fillFilters();render();$('sourceMsg').textContent=`已读取 Google Sheets：${products.length} SKU`;}catch(e){$('sourceMsg').textContent='读取失败，请确认 Sheet 已发布为 CSV'}};
function parseCSV(txt){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<txt.length;i++){const c=txt[i],n=txt[i+1];if(c==='"'){if(quoted&&n==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());cell='';if(row.some(v=>v!==''))rows.push(row);row=[]}else cell+=c}row.push(cell.trim());if(row.some(v=>v!==''))rows.push(row);if(!rows.length)return[];const h=rows.shift().map(x=>x.replace(/^\uFEFF/,''));return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
$('sheetUrl').value=localStorage.sheetUrl||'';fillFilters();render();