const demo=[
{brand:'Toshiba',model:'GR-RS910WI-PMTH(06)',image:'',type:'SBS',channel:'Power Buy',grossL:711,netL:711,door:'玻璃',iceMaker:'No',officialPrice:35990,promoPrice:28990,monthlySales:'',sellingPoints:'711L / Origin Inverter / Pure Air Turbo / TSmartLife',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/TOSHIBA-Side-by-Side-Refrigerator-25-1-Cubic-Inverter-Grey-GR-RS910WI-PMTH06-306586'},
{brand:'Toshiba',model:'GR-RS905WIA-PGTH(22)',image:'',type:'SBS',channel:'Power Buy',grossL:711,netL:711,door:'黑色玻璃',iceMaker:'Yes',officialPrice:42990,promoPrice:29990,monthlySales:'',sellingPoints:'711L / Pure Air Turbo / 自动制冰 / Pure Ice / TSmartLife',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/TOSHIBA-Side-by-Side-Refrigerator-25-1-Cubic-Inverter-Black-GR-RS905WIA-PGTH22-306583'},
{brand:'Samsung',model:'RS62R5001B4/ST',image:'',type:'SBS',channel:'Power Buy',grossL:655,netL:655,door:'Inox Gray',iceMaker:'待核实',officialPrice:36990,promoPrice:31444,monthlySales:'',sellingPoints:'655L / SpaceMax / All-around Cooling / Digital Inverter',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/samsung-os-%E0%B8%95%E0%B8%B9%E0%B9%89%E0%B9%80%E0%B8%A2%E0%B9%87%E0%B8%99-sbs-23-1-%E0%B8%84%E0%B8%B4%E0%B8%A7-samsung-rs62r5001b4st-263270'},
{brand:'Samsung',model:'RS70F65Q2FST',image:'',type:'SBS',channel:'Power Buy',grossL:655,netL:655,door:'Black Doi',iceMaker:'Yes',officialPrice:30990,promoPrice:24990,monthlySales:'',sellingPoints:'655L / SpaceMax / AI Inverter / Wi-Fi / SmartThings',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-SpaceMax-Technology-Side-by-Side-Refrigerator-23-1-Cubic-Inverter-Black-Doi-RS70F65Q2FST-304751'},
{brand:'Samsung',model:'RS70F65K1BST',image:'',type:'SBS',channel:'Power Buy',grossL:635,netL:635,door:'Clean Black',iceMaker:'Yes',officialPrice:48990,promoPrice:29990,monthlySales:'',sellingPoints:'635L / SpaceMax / AI Inverter / Wi-Fi / 冰水一体',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-SpaceMax-Technology-Side-by-Side-Refrigerator-22-4-Cubic-Inverter-Clean-Black-RS70F65K1BST-304745'},
{brand:'Samsung',model:'RS80F65G1FST',image:'',type:'SBS',channel:'Power Buy',grossL:627,netL:627,door:'Black Doi',iceMaker:'Yes',officialPrice:54990,promoPrice:45990,monthlySales:'',sellingPoints:'627L / Food Beverage Showcase / Auto Open Door / AI Inverter',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-Food-Beverage-Showcase-Side-by-Side-Refrigerator-22-1-Cubic-Inverter-Black-Doi-RS80F65G1FST-304754'},
{brand:'Samsung',model:'RS90F65A2FST',image:'',type:'SBS',channel:'Power Buy',grossL:615,netL:615,door:'Black Doi',iceMaker:'Yes',officialPrice:80990,promoPrice:72990,monthlySales:'',sellingPoints:'615L / Family Hub / AI Inverter / Wi-Fi / 冰水一体',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-Family-Hub-Side-by-Side-Refrigerator-21-7-Cubic-Inverter-Black-Doi-RS90F65A2FST-304757'},
{brand:'Samsung',model:'RS90F65D2FST',image:'',type:'SBS',channel:'Power Buy',grossL:615,netL:615,door:'Black Doi',iceMaker:'Yes',officialPrice:64990,promoPrice:56990,monthlySales:'',sellingPoints:'615L / 9-inch LCD AI Home / Bixby / SmartThings',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/SAMSUNG-LCD-AI-Home-Side-by-Side-Refrigerator-21-7-Cubic-Inverter-Black-Doi-RS90F65D2FST-304760'},
{brand:'LG',model:'GC-B257KGHW.ABMPLMT',image:'',type:'SBS',channel:'Power Buy',grossL:664,netL:664,door:'黑色玻璃',iceMaker:'No',officialPrice:32990,promoPrice:28590,monthlySales:'',sellingPoints:'664L / Smart Inverter / LinearCooling / Multi Air Flow',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/LG-Side-by-Side-Refrigerator-23-4-Cubic-Inverter-Black-Glass-GC-B257KGHW-ABMPLMT-306752'},
{brand:'LG',model:'GC-B257KLJW.APYPLMT',image:'',type:'SBS',channel:'Power Buy',grossL:664,netL:664,door:'银色',iceMaker:'待核实',officialPrice:28900,promoPrice:24890,monthlySales:'',sellingPoints:'664L / Smart Inverter / Multi Air Flow / 节能',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/LG-Side-by-Side-Refrigerator-23-4-Cubic-Inverter-Silver-GC-B257KLJW-APYPLMT-303177'},
{brand:'LG',model:'GC-X257ELEP.APYPLMT',image:'',type:'SBS',channel:'Power Buy',grossL:'',netL:'待核实',door:'银色',iceMaker:'待核实',officialPrice:52990,promoPrice:41900,monthlySales:'',sellingPoints:'22.2 cu.ft / Inverter / 高端系列',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/category/home-appliance/refrigerators/side-by-side-refrigerators'},
{brand:'Haier',model:'HRF-SBS636MS',image:'',type:'SBS',channel:'Power Buy',grossL:616,netL:616,door:'黑色',iceMaker:'待核实',officialPrice:25990,promoPrice:19490,monthlySales:'',sellingPoints:'616L / Twin Inverter / H-Deo Fresh / HCS Plus / Multi Airflow',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/HAIER-Side-by-Side-Refrigerator-21-7-Cubic-Inverter-Black-HRF-SBS636MS-296070'},
{brand:'Haier',model:'HRF-SBS636IW',image:'',type:'SBS',channel:'Power Buy',grossL:616,netL:616,door:'黑色',iceMaker:'Yes',officialPrice:37990,promoPrice:32841,monthlySales:'',sellingPoints:'616L / Auto Ice / H-Deo Fresh / Haismart',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/HAIER-Side-by-Side-Refrigerator-21-8-Cubic-Black-HRF-SBS636IW-302737'},
{brand:'Hitachi',model:'HRSN9713ESUTH',image:'',type:'SBS',channel:'Power Buy',grossL:656,netL:656,door:'黑色',iceMaker:'Twist Ice Maker',officialPrice:27990,promoPrice:23999,monthlySales:'',sellingPoints:'656L / Dual Surround Cooling / Triple Power Filter / Selectable Zone',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/HITACHI-Side-by-Side-Refrigerator-23-2-Cubic-Inverter-Black-HRSN9713ESUTH-307251'},
{brand:'Hitachi',model:'HRSN9698ESICMGWTH',image:'',type:'SBS',channel:'Power Buy',grossL:637,netL:637,door:'哑光玻璃白',iceMaker:'Yes',officialPrice:44990,promoPrice:41990,monthlySales:'',sellingPoints:'637L / 自动制冰与出水 / Dual Sensor / HOMEWHIZ',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/HITACHI-Skyline-Luxury-Side-by-Side-Refrigerator-22-5-Cubic-Inverter-Matte-Glass-White-HRSN9698ESICMGWTH-313903'},
{brand:'Electrolux',model:'ESE6205B-B',image:'',type:'SBS',channel:'Power Buy',grossL:624,netL:624,door:'黑色玻璃',iceMaker:'待核实',officialPrice:38990,promoPrice:28990,monthlySales:'',sellingPoints:'624L / GreenZone / DynamicAir / Inverter / QuickFreeze',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/ELECTROLUX-Side-by-Side-Refrigerator-22-Cubic-Inverter-Black-Glass-ESE6205B-B-306352'},
{brand:'Electrolux',model:'ESE6200B-B',image:'',type:'SBS',channel:'Power Buy',grossL:624,netL:624,door:'哑光黑',iceMaker:'待核实',officialPrice:35990,promoPrice:26990,monthlySales:'',sellingPoints:'624L / GreenZone / DynamicAir / Inverter / QuickChill',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/ELECTROLUX-Side-by-Side-Refrigerator-22-Cubic-Inverter-Matte-Black-ESE6200B-B-306355'},
{brand:'TCL',model:'RT62MPSBG',image:'',type:'SBS',channel:'Power Buy',grossL:631,netL:631,door:'不锈钢',iceMaker:'Twist Ice Maker',officialPrice:18490,promoPrice:15490,monthlySales:'',sellingPoints:'631L / Twin Eco Inverter / Power Cool & Freeze / AAT',updated:'2026-09-15',link:'https://www.powerbuy.co.th/en/product/TCL-P650-Series-Side-by-Side-Refrigerator-22-3-Cubic-Inverter-Stainless-RT62MPSBG-304128'},
{brand:'Sharp',model:'SJ-SBS600P-DK',image:'',type:'SBS',channel:'HomePro',grossL:599.6,netL:599.6,door:'钢板',iceMaker:'待核实',officialPrice:'',promoPrice:'',monthlySales:'',sellingPoints:'约600L / J-Tech Inverter / Ag+Cu Nano Deodorizer',updated:'2026-09-15',link:'https://www.homepro.co.th/p/1254182'},
{brand:'Hisense',model:'RS808N4TBMU',image:'',type:'SBS',channel:'Central',grossL:612.7,netL:612.7,door:'Mirror Glass',iceMaker:'待核实',officialPrice:31990,promoPrice:25191,monthlySales:'',sellingPoints:'612.7L / All Zone Active Hygiene+ / Inverter Pro Super Freeze / Multi Air Flow / Digital Touch',updated:'2026-09-15',link:'https://hisense.co.th/product/rs808n4tbmu/'}
];
let products=[...demo];const $=id=>document.getElementById(id);const brandColors={LG:'#c51d48',Haier:'#0874c9',Toshiba:'#e01c73',Hisense:'#078f91',Samsung:'#2372c7',Hitachi:'#ec6a2c',Sharp:'#7c55c8',TCL:'#ef7b25',Electrolux:'#2f8c69'};const money=n=>n!==''&&n!=null&&!isNaN(Number(n))?'฿'+Number(n).toLocaleString('en-US'):'—';const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[m]));
function fillFilters(){for(const [id,key] of [['brand','brand'],['type','type'],['channel','channel']]){const vals=[...new Set(products.map(x=>x[key]).filter(Boolean))].sort();$(id).innerHTML='<option value="">All / 全部</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}}
function inCap(x,v){if(!v)return true;const n=Number(x.netL);if(!Number.isFinite(n))return false;if(v==='700+')return n>=700;if(v==='650-699')return n>=650&&n<700;if(v==='600-649')return n>=600&&n<650;if(v==='500-599')return n>=500&&n<600;if(v==='400-499')return n>=400&&n<500;return n>=300&&n<400}
function inPrice(x,v){if(!v)return true;const n=Number(x.promoPrice);if(!Number.isFinite(n))return false;const [a,b]=v.split('-').map(Number);return n>=a&&n<=b}
function filtered(){const s=$('search').value.trim().toLowerCase(),b=$('brand').value,t=$('type').value,ch=$('channel').value,c=$('capacity').value,p=$('price').value;return products.filter(x=>(!b||x.brand===b)&&(!t||x.type===t)&&(!ch||x.channel===ch)&&inCap(x,c)&&inPrice(x,p)&&(!s||JSON.stringify(x).toLowerCase().includes(s)))}
function avg(list){const a=list.map(x=>Number(x.promoPrice)).filter(Number.isFinite);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):null}
function renderStats(list){const names=['LG','Haier','Toshiba','Hisense'];let h=`<div class="stat" style="--accent:#07878a"><small>RESULTS / 当前结果</small><b>${list.length}</b><em>SKU</em></div>`;for(const n of names){const rows=list.filter(x=>x.brand===n);h+=`<div class="stat" style="--accent:${brandColors[n]}"><small>${n.toUpperCase()} AVG / 均价</small><b>${avg(rows)==null?'—':money(avg(rows))}</b><em>${rows.length} SKU</em></div>`}const ta=avg(list.filter(x=>x.brand==='Toshiba')),hi=avg(list.filter(x=>x.brand==='Hisense')),gap=ta!=null&&hi!=null?ta-hi:null;h+=`<div class="stat ${gap>0?'negative':''}" style="--accent:#07878a"><small>TOSHIBA - HISENSE</small><b>${gap==null?'—':(gap>=0?'+':'')+money(gap)}</b><em>Average price gap</em></div>`;$('stats').innerHTML=h}
function imageHtml(x){return x.image?`<img src="${esc(x.image)}" alt="${esc(x.model)}" loading="lazy" onerror="this.style.display='none';this.parentNode.classList.add('imgFallback')">`:`<div class="imgFallback"><span>PRODUCT<br>IMAGE</span><small>${esc(x.brand)}</small></div>`}
function card(x){const d=Number(x.officialPrice)&&Number(x.promoPrice)?Math.round((1-Number(x.promoPrice)/Number(x.officialPrice))*100):0;return `<button class="productCard" style="--brand:${brandColors[x.brand]||'#07878a'}" data-model="${esc(x.model)}"><div class="productImg">${imageHtml(x)}</div><div class="pcBody"><div class="pcTop"><span>${esc(x.channel||x.type||'')}</span>${d?`<i>-${d}%</i>`:''}</div><div class="pcModel">${esc(x.model)}</div><div class="pcMeta">${esc(x.netL||x.grossL||'—')}L · ${esc(x.door||'')}</div><div class="pcPrice"><b>${money(x.promoPrice)}</b><s>${money(x.officialPrice)}</s></div><div class="pcPoint">${esc(x.sellingPoints||'—')}</div>${x.monthlySales?`<div class="sales">月销量 <b>${esc(x.monthlySales)}</b></div>`:''}</div></button>}
function renderMap(list){const brands=[...new Set(list.map(x=>x.brand))],priced=list.filter(x=>Number.isFinite(Number(x.promoPrice))),prices=[...new Set(priced.map(x=>Number(x.promoPrice)))].sort((a,b)=>b-a);let html=`<div class="map" style="--cols:${brands.length}"><div class="mapHeader"><div class="priceHead">PROMO PRICE</div>${brands.map(b=>`<div class="brandHead" style="--brand:${brandColors[b]||'#07878a'}">${esc(b)}</div>`).join('')}</div>`;for(const price of prices){html+=`<div class="mapRow"><div class="priceCell">${money(price)}</div>`;for(const b of brands){const x=list.find(v=>v.brand===b&&Number(v.promoPrice)===price);html+=`<div class="productCell">${x?card(x):''}</div>`}html+='</div>'}html+='</div>';if(!prices.length)html='<div class="noData">当前筛选没有可用于价格对阵的产品。</div>';$('mapWrap').innerHTML=html;document.querySelectorAll('.productCard').forEach(el=>el.addEventListener('click',()=>openModal(products.find(x=>x.model===el.dataset.model))))}
function renderTable(list){$('tableCount').textContent=`${list.length} 个 SKU`;$('productTable').innerHTML=list.slice().sort((a,b)=>(Number(a.promoPrice)||Infinity)-(Number(b.promoPrice)||Infinity)).map(x=>`<tr data-model="${esc(x.model)}"><td><div class="miniProduct"><div>${imageHtml(x)}</div><b>${esc(x.model)}</b></div></td><td><strong style="color:${brandColors[x.brand]||'#07878a'}">${esc(x.brand)}</strong><small>${esc(x.channel||'')}</small></td><td>${esc(x.netL||x.grossL||'—')}L</td><td class="price">${money(x.promoPrice)}</td><td>${money(x.officialPrice)}</td><td>${x.monthlySales?esc(x.monthlySales):'—'}</td><td>${esc(x.door||'—')} / ${esc(x.iceMaker||'—')}</td><td>${esc(x.updated||'—')}</td></tr>`).join('');document.querySelectorAll('#productTable tr').forEach(el=>el.addEventListener('click',()=>openModal(products.find(x=>x.model===el.dataset.model))))}
function renderBubble(list){const rows=list.filter(x=>Number.isFinite(Number(x.promoPrice))&&Number.isFinite(Number(x.netL)));if(!rows.length){$('bubbleChart').innerHTML='<div class="noData">需要同时有价格和容量才能绘制气泡图。</div>';return}const W=980,H=410,pad={l:70,r:25,t:25,b:55},xs=rows.map(x=>Number(x.netL)),ys=rows.map(x=>Number(x.promoPrice)),xmin=Math.min(...xs)-15,xmax=Math.max(...xs)+15,ymin=Math.max(0,Math.min(...ys)-5000),ymax=Math.max(...ys)+5000,sx=x=>pad.l+(x-xmin)/(xmax-xmin)*(W-pad.l-pad.r),sy=y=>H-pad.b-(y-ymin)/(ymax-ymin)*(H-pad.t-pad.b);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img"><line x1="${pad.l}" y1="${H-pad.b}" x2="${W-pad.r}" y2="${H-pad.b}" class="axis"/><line x1="${pad.l}" y1="${pad.t}" x2="${pad.l}" y2="${H-pad.b}" class="axis"/><text x="${W/2}" y="${H-12}" class="axisLabel">Capacity / 容量 (L)</text><text x="18" y="${H/2}" transform="rotate(-90 18 ${H/2})" class="axisLabel">Promo price / 促销价</text>`;for(let i=0;i<5;i++){const xv=xmin+(xmax-xmin)*i/4,yv=ymin+(ymax-ymin)*i/4;svg+=`<text x="${sx(xv)}" y="${H-35}" class="tick">${Math.round(xv)}</text><text x="${pad.l-10}" y="${sy(yv)+4}" text-anchor="end" class="tick">${Math.round(yv/1000)}k</text>`}rows.forEach(x=>{const sales=Number(x.monthlySales),r=Number.isFinite(sales)?Math.min(30,7+Math.sqrt(sales)*2):7;svg+=`<g class="bubble" data-model="${esc(x.model)}"><circle cx="${sx(Number(x.netL))}" cy="${sy(Number(x.promoPrice))}" r="${r}" fill="${brandColors[x.brand]||'#07878a'}" fill-opacity=".72"/><text x="${sx(Number(x.netL))+r+3}" y="${sy(Number(x.promoPrice))+3}" class="bubbleLabel">${esc(x.brand)} ${esc(x.model)}</text></g>`});svg+='</svg><div class="legend">'+Object.entries(brandColors).map(([b,c])=>`<span><i style="background:${c}"></i>${b}</span>`).join('')+'</div>';$('bubbleChart').innerHTML=svg;document.querySelectorAll('.bubble').forEach(el=>el.addEventListener('click',()=>openModal(products.find(x=>x.model===el.dataset.model))))}
function openModal(x){if(!x)return;$('modalBody').innerHTML=`<div class="modalGrid"><div class="modalImage">${imageHtml(x)}</div><div><div class="eyebrow">${esc(x.brand)} · ${esc(x.channel||'')}</div><h2>${esc(x.model)}</h2><div class="modalPrice">${money(x.promoPrice)} <s>${money(x.officialPrice)}</s></div><div class="detailGrid"><span>容量</span><b>${esc(x.netL||x.grossL||'—')}L</b><span>门板</span><b>${esc(x.door||'—')}</b><span>自动制冰</span><b>${esc(x.iceMaker||'—')}</b><span>月销量</span><b>${esc(x.monthlySales||'未填')}</b><span>更新时间</span><b>${esc(x.updated||'—')}</b></div><p class="selling">${esc(x.sellingPoints||'—')}</p>${x.link?`<a class="visit" href="${esc(x.link)}" target="_blank" rel="noopener">打开零售商 / 官方页面 ↗</a>`:''}</div></div>`;$('modal').classList.add('show')}
function render(){const list=filtered();renderStats(list);renderMap(list);renderBubble(list);renderTable(list);$('topUpdated').textContent=new Date().toLocaleString('zh-CN',{hour12:false})}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i],nx=text[i+1];if(ch==='"'&&q&&nx==='"'){cell+='"';i++;continue}if(ch==='"'){q=!q;continue}if(ch===','&&!q){row.push(cell);cell='';continue}if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&nx==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))rows.push(row);row=[];continue}cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}const headers=(rows.shift()||[]).map(x=>x.trim());return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]||'').trim()]))).filter(x=>x.model)}
function loadSheet(){const url=$('sheetUrl').value.trim();if(!url){$('sourceMsg').textContent='请先粘贴 Google Sheets CSV 地址';return}localStorage.setItem('refSheetUrl',url);$('sourceMsg').textContent='正在读取 Sheet…';fetch(url).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.text()}).then(text=>{const rows=parseCSV(text);if(!rows.length)throw new Error('没有读取到数据');products=rows;fillFilters();$('sourceMsg').textContent=`已读取 ${rows.length} 个 SKU · 数据来自 Google Sheets`;render()}).catch(e=>{$('sourceMsg').textContent='读取失败：请确认 Sheet 已发布为 CSV，且链接可公开访问。';console.error(e)})}
['search','brand','type','channel','capacity','price'].forEach(id=>$(id).addEventListener('input',render));$('reset').addEventListener('click',()=>{['search','brand','type','channel','capacity','price'].forEach(id=>$(id).value='');render()});$('refreshBtn').addEventListener('click',()=>location.reload());$('saveUrl').addEventListener('click',()=>{localStorage.setItem('refSheetUrl',$('sheetUrl').value.trim());$('sourceMsg').textContent='地址已保存'});$('loadSheet').addEventListener('click',loadSheet);$('closeModal').addEventListener('click',()=>$('modal').classList.remove('show'));$('modal').addEventListener('click',e=>{if(e.target.id==='modal')$('modal').classList.remove('show')});const saved=localStorage.getItem('refSheetUrl');if(saved)$('sheetUrl').value=saved;fillFilters();render();
