const demo=[
{brand:'Toshiba',model:'GR-RS910WI-PMTH(06)',image:'',type:'SBS',grossL:700,netL:650,door:'Glass',iceMaker:'Yes',officialPrice:69990,promoPrice:49990,monthlySales:120,sellingPoints:'超大容量 / 自动制冰 / 玻璃门板',updated:'2026-09-15',link:''},
{brand:'Samsung',model:'RT62MPSBG',image:'',type:'2 Door',grossL:620,netL:575,door:'Steel',iceMaker:'No',officialPrice:45990,promoPrice:39990,monthlySales:180,sellingPoints:'数字变频 / 大容量 / 节能',updated:'2026-09-15',link:''},
{brand:'LG',model:'GC-B257JQYL',image:'',type:'SBS',grossL:674,netL:635,door:'Steel',iceMaker:'Yes',officialPrice:52990,promoPrice:44990,monthlySales:150,sellingPoints:'Door Cooling+ / 自动制冰',updated:'2026-09-15',link:''},
{brand:'Haier',model:'HRF-775SI',image:'',type:'Multi Door',grossL:775,netL:680,door:'Glass',iceMaker:'Yes',officialPrice:59990,promoPrice:42990,monthlySales:95,sellingPoints:'多门 / 自动制冰 / 超大容量',updated:'2026-09-15',link:''},
{brand:'Hitachi',model:'R-WB640VGV0',image:'',type:'Multi Door',grossL:638,netL:569,door:'Glass',iceMaker:'Yes',officialPrice:69990,promoPrice:54990,monthlySales:75,sellingPoints:'日立保鲜技术 / 自动制冰',updated:'2026-09-15',link:''},
{brand:'Sharp',model:'SJ-FX79T-SL',image:'',type:'Multi Door',grossL:729,netL:648,door:'Steel',iceMaker:'Yes',officialPrice:57990,promoPrice:45990,monthlySales:110,sellingPoints:'J-Tech Inverter / 多门',updated:'2026-09-15',link:''}
];
let products=[...demo];const $=id=>document.getElementById(id);const money=n=>n?'฿'+Number(n).toLocaleString('en-US'):'—';
function fillFilters(){['brand','type'].forEach(k=>{const vals=[...new Set(products.map(x=>x[k]).filter(Boolean))].sort();$(k).innerHTML='<option value="">全部'+(k==='brand'?'品牌':'类型')+'</option>'+vals.map(v=>`<option>${v}</option>`).join('')})}
function inCap(x,v){if(!v)return true;let n=+x.netL||0;if(v==='600+')return n>=600;if(v==='500-599')return n>=500&&n<600;if(v==='400-499')return n>=400&&n<500;return n>=300&&n<400}
function inPrice(x,v){if(!v)return true;let [a,b]=v.split('-').map(Number);return +x.promoPrice>=a&&+x.promoPrice<=b}
function render(){const b=$('brand').value,t=$('type').value,c=$('capacity').value,p=$('price').value,s=$('search').value.trim().toLowerCase();const list=products.filter(x=>(!b||x.brand===b)&&(!t||x.type===t)&&inCap(x,c)&&inPrice(x,p)&&(!s||JSON.stringify(x).toLowerCase().includes(s)));$('count').textContent=list.length;$('brands').textContent=new Set(list.map(x=>x.brand)).size;const prices=list.map(x=>+x.promoPrice).filter(Boolean);$('avg').textContent=prices.length?money(Math.round(prices.reduce((a,b)=>a+b,0)/prices.length)):'—';$('updated').textContent=list.map(x=>x.updated).sort().pop()||'—';$('resultText').textContent=`${list.length} 个型号`;$('grid').innerHTML=list.map(x=>`<article class="card"><div class="photo">${x.image?`<img src="${x.image}" alt="${x.model}">`:'产品图片'}</div><div class="content"><div class="brand">${x.brand}</div><div class="model">${x.model}</div><div class="tags"><span class="tag">${x.type||'—'}</span><span class="tag">净容积 ${x.netL||'—'}L</span><span class="tag">${x.door||'—'}门板</span><span class="tag">${x.iceMaker==='Yes'?'自动制冰':'无自动制冰'}</span></div><div class="price"><span class="promo">${money(x.promoPrice)}</span><span class="old">${money(x.officialPrice)}</span></div><div class="sales"><span>月销量</span><b>${x.monthlySales||'—'}</b></div><div class="points">${x.sellingPoints||''}</div>${x.link?`<a class="link" href="${x.link}" target="_blank">查看商品 →</a>`:''}</div></article>`).join('')||'<div>没有符合条件的型号。</div>'}
['brand','type','capacity','price','search'].forEach(id=>$(id).addEventListener('input',render));$('reset').onclick=()=>{['brand','type','capacity','price','search'].forEach(id=>$(id).value='');render()};
$('saveUrl').onclick=()=>{localStorage.sheetUrl=$('sheetUrl').value.trim();$('sourceMsg').textContent='数据源地址已保存';};$('loadSheet').onclick=async()=>{const u=$('sheetUrl').value.trim()||localStorage.sheetUrl;if(!u)return $('sourceMsg').textContent='请先填写 Google Sheets CSV 地址';try{const txt=await fetch(u).then(r=>r.text());products=parseCSV(txt);if(!products.length)throw Error();fillFilters();render();$('sourceMsg').textContent='已读取 Google Sheets 数据';}catch(e){$('sourceMsg').textContent='读取失败，请确认 Sheet 已发布为 CSV';}};
function parseCSV(txt){const rows=txt.trim().split(/\r?\n/).map(r=>r.split(',').map(v=>v.replace(/^"|"$/g,'').trim()));const h=rows.shift();return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]||''])))}
$('sheetUrl').value=localStorage.sheetUrl||'';fillFilters();render();